const schoolPrompt = (prompt) =>
  `個人情報を含まない架空・公開の内容で試します。${prompt}`;

const questPowers = {
  1: ["dialogue", "agency"],
  2: ["instruction", "dialogue"],
  3: ["finishing", "instruction"],
  4: ["finishing", "instruction"],
  5: ["dialogue", "instruction"],
  6: ["instruction", "finishing"],
  7: ["instruction", "dialogue"],
  8: ["dialogue", "instruction"],
  9: ["delegation", "instruction"],
  10: ["delegation", "dialogue"],
  11: ["delegation", "verification"],
  12: ["delegation", "safety"],
  13: ["safety", "verification"],
  14: ["delegation", "agency"],
  15: ["verification", "safety"],
  16: ["instruction", "safety"],
  17: ["verification", "safety"],
  18: ["finishing", "instruction"],
  19: ["agency", "dialogue"],
  20: ["finishing", "agency"],
  21: ["dialogue", "agency"],
  22: ["instruction", "dialogue"],
  23: ["dialogue", "agency"],
  24: ["agency", "finishing"],
  25: ["agency", "dialogue"],
  26: ["verification", "safety"],
  27: ["verification", "safety"],
  28: ["finishing", "agency"],
  29: ["delegation", "instruction"],
  30: ["delegation", "agency"],
};

const quest = ({
  id,
  area,
  title,
  ability,
  inputMode,
  daily,
  school,
  reflectPrompt,
  factCheck = { required: false, method: "" },
  related,
}) => {
  const [primaryPower, supportingPower] = questPowers[id];
  return {
    id,
    area,
    title,
    ability,
    inputMode,
    daily,
    school: {
      ...school,
      firstPrompt: schoolPrompt(school.firstPrompt),
    },
    reflectPrompt,
    safety: "児童・保護者・職員の名前や、個人が分かる情報、学校の機密情報は入力しません。",
    factCheck,
    related,
    primaryPower,
    supportingPower,
  };
};

export const quests = [
  quest({
    id: 1,
    area: "text",
    title: "AIに自己紹介せよ",
    ability: "普通の言葉で相談する",
    inputMode: "text",
    daily: {
      situation: "今日の過ごし方が決まらない",
      firstPrompt: "今日は少し時間があります。家で気軽にできる過ごし方を3つ提案してください。",
      followUp: "私は静かに過ごしたいです。その条件で考え直してください。",
    },
    school: {
      situation: "今の仕事をどこから始めるか迷う",
      firstPrompt: "小学校の教員です。今日やることが多く、どこから始めるか迷っています。整理を手伝ってください。",
      followUp: "私は短時間で終わる仕事から始めたいです。その考えを入れて並べてください。",
    },
    reflectPrompt: "AIの返事の中で、あなたに合うところと違うところはどこですか？",
    related: [5, 10],
  }),
  quest({
    id: 2,
    area: "text",
    title: "短い質問を投げてみよ",
    ability: "一文だけで尋ねる",
    inputMode: "text",
    daily: {
      situation: "身近な疑問を気軽に聞きたい",
      firstPrompt: "雨の日に家で気分転換する方法は？",
      followUp: "私は体を少し動かしたいので、その条件に合う案を一つ選んでください。",
    },
    school: {
      situation: "授業の導入を短く考えたい",
      firstPrompt: "架空の算数授業で、子どもが考えたくなる最初の問いは？",
      followUp: "私は答えが一つに決まらない問いが好みです。別の問いにしてください。",
    },
    reflectPrompt: "一文で聞いた答えは、あなたが知りたかったことに合っていましたか？",
    related: [1, 8],
  }),
  quest({
    id: 3,
    area: "text",
    title: "止まった文章を救え",
    ability: "続きを一緒に考える",
    inputMode: "text",
    daily: {
      situation: "短いメッセージの続きが浮かばない",
      firstPrompt: "「久しぶりです。元気にしていますか。」に続く、気軽な一文を3案ください。",
      followUp: "私はかしこまりすぎた感じに違和感があります。もっと普段の言葉にしてください。",
    },
    school: {
      situation: "架空のお便りの書き出しで止まった",
      firstPrompt: "架空の学級だよりの書き出し「夏休みまであと少しです。」に続く一文を考えてください。",
      followUp: "私は子どもの頑張りが伝わる文にしたいです。その考えを足してください。",
    },
    reflectPrompt: "AIの続きをそのまま使わず、あなたならどこを直しますか？",
    related: [6, 28],
  }),
  quest({
    id: 4,
    area: "text",
    title: "相手に届く言葉に変えよ",
    ability: "相手に合わせて言い換える",
    inputMode: "text",
    daily: {
      situation: "お願いをやわらかく伝えたい",
      firstPrompt: "「明日までに返してください」を、友人にやわらかく伝える言葉に変えてください。",
      followUp: "私は急がせたくないので、都合を尋ねる言い方に直してください。",
    },
    school: {
      situation: "架空の連絡文を読みやすくしたい",
      firstPrompt: "「提出期限を厳守してください」を、架空の保護者向けに穏やかに言い換えてください。",
      followUp: "私は理由も短く添えたいです。その考えを入れた文にしてください。",
    },
    reflectPrompt: "相手を思い浮かべたとき、あなたが採用したい言い方はどれですか？",
    related: [18, 28],
  }),
  quest({
    id: 5,
    area: "text",
    title: "「もう少し」で答えを変えよ",
    ability: "追加の一言で調整する",
    inputMode: "text",
    daily: {
      situation: "提案が自分には少し難しい",
      firstPrompt: "平日の夜にできる気分転換を3つ教えてください。",
      followUp: "私は疲れているので、もう少し手軽で10分以内の案に変えてください。",
    },
    school: {
      situation: "活動案を教室に合わせたい",
      firstPrompt: "架空の学級でできる短い交流活動を3つ考えてください。",
      followUp: "私は準備物なしで行いたいです。その条件でもう少し簡単にしてください。",
    },
    reflectPrompt: "どんな一言を足すと、答えがあなた向きになりましたか？",
    related: [1, 22],
  }),
  quest({
    id: 6,
    area: "text",
    title: "バラバラのメモをつなげよ",
    ability: "メモを文章にする",
    inputMode: "text",
    daily: {
      situation: "買い物の相談メモを文章にしたい",
      firstPrompt: "次の架空のメモを短い相談文にしてください。「土曜／駅前／昼ごろ／待ち合わせ」",
      followUp: "私は親しみやすい文が好みです。かたい部分を直してください。",
    },
    school: {
      situation: "公開用の行事メモを案内文にしたい",
      firstPrompt: "次の架空の公開メモを一文にしてください。「作品展／体育館／午後／上履き」",
      followUp: "私は持ち物を目立たせたいです。その考えで並びを変えてください。",
    },
    reflectPrompt: "できた文章に、あなたの言葉として残したくない表現はありませんか？",
    related: [3, 9],
  }),
  quest({
    id: 7,
    area: "text",
    title: "アイデアを10個集めよ",
    ability: "選択肢を広げる",
    inputMode: "text",
    daily: {
      situation: "休日の小さな楽しみを増やしたい",
      firstPrompt: "家でできる、お金のかからない小さな楽しみを10個出してください。",
      followUp: "私は音を出さずにできる案が好みです。合うものを残し、別案も足してください。",
    },
    school: {
      situation: "架空の授業の振り返り方法を増やしたい",
      firstPrompt: "個人情報なしでできる、授業の短い振り返り方法を10個考えてください。",
      followUp: "私は3分以内でできる方法を選びたいです。その条件で候補を絞ってください。",
    },
    reflectPrompt: "10個のうち、あなたが試す案・変える案・使わない案はどれですか？",
    related: [20, 25],
  }),
  quest({
    id: 8,
    area: "text",
    title: "分かるまで聞き直せ",
    ability: "説明方法を変えさせる",
    inputMode: "text",
    daily: {
      situation: "聞いた説明が難しかった",
      firstPrompt: "「クラウド保存」を初めて聞く人向けに説明してください。",
      followUp: "私はまだイメージできません。身近なたとえを一つ使って説明し直してください。",
    },
    school: {
      situation: "公開された教育用語を簡単に理解したい",
      firstPrompt: "公開資料に出てくる「協働的な学び」を、難しい言葉を避けて説明してください。",
      followUp: "私は教室での場面を思い浮かべたいです。架空の例を一つ加えてください。",
    },
    reflectPrompt: "どの説明なら、あなた自身の言葉で言い直せそうですか？",
    related: [2, 15],
  }),
  quest({
    id: 9,
    area: "text",
    title: "長い話から必要なことを選べ",
    ability: "困りごとを言葉で説明して整理する",
    inputMode: "text",
    daily: {
      situation: "いくつも重なった困りごとを整理したい",
      firstPrompt: "朝は時間がなく、片付けも途中で、出かける準備も進みません。困りごとを3つに分けてください。",
      followUp: "私は出かける準備を先にしたいです。その考えに合わせて順番を変えてください。",
    },
    school: {
      situation: "架空の仕事の混み合いを整理したい",
      firstPrompt: "架空の状況です。教材準備、公開資料の確認、会議の準備が重なっています。やることを整理してください。",
      followUp: "私は期限が近いものから考えたいです。その条件で質問を返してください。",
    },
    reflectPrompt: "AIが分けた中で、あなたにとって本当に大事な困りごとはどれですか？",
    related: [6, 19],
  }),
  quest({
    id: 10,
    area: "text",
    title: "小さな困りごとを相談せよ",
    ability: "使い道を自分の生活から探す",
    inputMode: "text",
    daily: {
      situation: "毎日の小さな面倒を減らしたい",
      firstPrompt: "夕食後の片付けを始めやすくする小さな工夫を3つ考えてください。",
      followUp: "私は一度に全部するのは合いません。最初の一歩だけに直してください。",
    },
    school: {
      situation: "日々の小さな校務を楽にしたい",
      firstPrompt: "架空の校務として、机上の公開資料を短時間で整理する工夫を3つください。",
      followUp: "私は毎日5分なら続けられます。その考えに合う方法だけ残してください。",
    },
    reflectPrompt: "あなたの生活や仕事で、AIを材料として試せる小さな場面はどこですか？",
    related: [1, 29],
  }),
  quest({
    id: 11,
    area: "media",
    title: "二つの候補をくらべよ",
    ability: "比較する",
    inputMode: "text",
    daily: {
      situation: "二つの道具のどちらにするか迷う",
      firstPrompt: "架空の候補A「軽い・小さい」と候補B「丈夫・少し重い」を、持ち歩きやすさで比べてください。",
      followUp: "私は軽さを優先します。その好みを入れても、見落とす条件がないか教えてください。",
    },
    school: {
      situation: "二つの公開教材案を比べたい",
      firstPrompt: "架空の教材A「短時間」と教材B「話し合い中心」を、準備時間と参加しやすさで比べてください。",
      followUp: "私は全員が参加しやすい方を重く見ます。その考えで比較し直してください。",
    },
    reflectPrompt: "比べた結果を見て、あなたは何を基準に採用・不採用を決めますか？",
    factCheck: {
      required: true,
      method: "商品の公式説明や教材の原文に戻り、比較した条件を一つずつ照合します。",
    },
    related: [22, 24],
  }),
  quest({
    id: 12,
    area: "media",
    title: "写真を撮って聞いてみよ",
    ability: "初めて写真を撮影・添付する",
    inputMode: "camera",
    daily: {
      situation: "身の回りの物の使い道を考えたい",
      firstPrompt: "個人情報が写っていない、公開可能な机上の文房具を撮影しました。写っている物を使った整理の案を3つください。",
      followUp: "私は机を広く使いたいです。その条件に合わない案は外してください。",
    },
    school: {
      situation: "公開できる備品写真から使い方を考えたい",
      firstPrompt: "教室を想定した備品写真です。授業での使い方を3つ考えてください。",
      followUp: "私は準備時間を短くしたいです。その考えを入れて案を選び直してください。",
    },
    reflectPrompt: "写真を見たAIの説明に、あなたが見て違うと思う点はありませんか？",
    related: [13, 17],
  }),
  quest({
    id: 13,
    area: "media",
    title: "写真から忘れ物を防げ",
    ability: "写真を添付してチェックリスト化する",
    inputMode: "camera",
    daily: {
      situation: "外出前の持ち物を確認したい",
      firstPrompt: "名前や住所が写っていない、公開できる持ち物の写真です。見えている物だけをチェックリストにしてください。",
      followUp: "私は飲み物も必要だと思います。写真にない物は推測と分かるように分けてください。",
    },
    school: {
      situation: "架空行事の公開用備品を確認したい",
      firstPrompt: "備品写真です。見えている物を確認表にしてください。",
      followUp: "私は延長コードも確認したいです。画像で確認済みか、追加候補かを分けてください。",
    },
    reflectPrompt: "AIの一覧と実物を見比べて、あなたが追加・削除する物は何ですか？",
    related: [12, 17],
  }),
  quest({
    id: 14,
    area: "media",
    title: "無理のない予定に組み直せ",
    ability: "予定を調整する",
    inputMode: "paste",
    daily: {
      situation: "架空の一日の予定が詰まりすぎている",
      firstPrompt: "次の架空予定を無理のない順にしてください。「買い物30分、休憩20分、片付け40分、散歩20分」",
      followUp: "私は休憩を先に取りたいです。その考えを入れ、余白も作ってください。",
    },
    school: {
      situation: "公開行事の架空準備予定を整えたい",
      firstPrompt: "架空の公開予定です。「資料確認20分、会場準備30分、休憩10分、片付け20分」を組み直してください。",
      followUp: "私は会場準備を優先したいです。その条件で無理がないか見直してください。",
    },
    reflectPrompt: "AIの予定案のうち、あなたが現実に合わせて動かす時間はどこですか？",
    related: [9, 22],
  }),
  quest({
    id: 15,
    area: "media",
    title: "むずかしい説明をやさしくせよ",
    ability: "文章・文書を渡して簡単にし原文へ戻る",
    inputMode: "document",
    daily: {
      situation: "公開された説明文を読みやすくしたい",
      firstPrompt: "個人情報を含まない公開文書を添付しました。指定した一段落を、初めて読む人向けに短く説明してください。",
      followUp: "私は「必ず」と読める表現に違和感があります。原文のどこに書かれているか示してください。",
    },
    school: {
      situation: "公的な教育資料の一節を理解したい",
      firstPrompt: "添付した公的資料から、指定した一段落だけをやさしく説明してください。",
      followUp: "私は意味が変わっていないか心配です。原文の該当箇所と説明を並べてください。",
    },
    reflectPrompt: "やさしい説明を原文と比べ、あなたが直す必要を感じた部分はどこですか？",
    factCheck: {
      required: true,
      method: "添付した原文の該当段落へ戻り、省略や意味の変化がないか文ごとに確かめます。",
    },
    related: [8, 26],
  }),
  quest({
    id: 16,
    area: "media",
    title: "聞くべき質問を集めよ",
    ability: "質問を作る",
    inputMode: "camera",
    daily: {
      situation: "公開イベントの掲示写真を見て質問を考えたい",
      firstPrompt: "個人情報が写っていない架空イベントの掲示写真です。参加前に確認する質問を5つ作ってください。",
      followUp: "私は持ち物が気になります。その考えを入れ、掲示に答えがある質問は分けてください。",
    },
    school: {
      situation: "公開掲示の写真から確認事項を考えたい",
      firstPrompt: "イベント掲示の写真です。担当者に確認する質問を5つ考えてください。",
      followUp: "私は安全面を先に確かめたいです。その条件で質問の順番を変えてください。",
    },
    reflectPrompt: "AIが作った質問から、あなたが本当に聞きたいものをどう選びますか？",
    related: [12, 25],
  }),
  quest({
    id: 17,
    area: "media",
    title: "画像の見落としを探せ",
    ability: "写真・スクリーンショットを添付して観点を増やす",
    inputMode: "image",
    daily: {
      situation: "公開画面のスクリーンショットを別の目で見たい",
      firstPrompt: "個人情報を隠した架空の案内画面です。初めて見る人が迷いそうな点を挙げてください。",
      followUp: "私は文字の小ささも気になります。その違和感を加えて、重要な順にしてください。",
    },
    school: {
      situation: "公開用資料の画像に見落としがないか探したい",
      firstPrompt: "案内資料の画像です。読み手が迷う点を観点別に挙げてください。",
      followUp: "私は日付の見つけにくさが気になります。その考えを含めて見直してください。",
    },
    reflectPrompt: "AIの指摘を画像で確かめ、あなたが採用する指摘と見送る指摘はどれですか？",
    factCheck: {
      required: true,
      method: "AIの指摘を原文に当たる元画像と一つずつ照らし合わせ、実際に見える内容だけを残します。",
    },
    related: [13, 27],
  }),
  quest({
    id: 18,
    area: "media",
    title: "角の立たない言い方を探せ",
    ability: "頼み方・断り方を考える",
    inputMode: "paste",
    daily: {
      situation: "誘いをやわらかく断りたい",
      firstPrompt: "「今回は参加できません」を、相手への感謝が伝わる短い文にしてください。",
      followUp: "私は次の約束まではできません。その条件を守った言い方に直してください。",
    },
    school: {
      situation: "架空の依頼への返事を穏やかにしたい",
      firstPrompt: "架空の依頼への返事「今週中は難しいです」を、個人情報なしの丁寧な文にしてください。",
      followUp: "私は代案なら一つ出せます。その考えを添えつつ、約束しすぎない文にしてください。",
    },
    reflectPrompt: "AIの文を声に出したとき、あなたらしくないと感じる表現はどこですか？",
    related: [4, 23],
  }),
  quest({
    id: 19,
    area: "media",
    title: "頭の中のもやもやを分けよ",
    ability: "考えを整理する",
    inputMode: "text",
    daily: {
      situation: "やりたいことと心配が混ざっている",
      firstPrompt: "出かけたい気持ちはありますが、疲れも天気も気になります。気持ち・事実・決めることに分けてください。",
      followUp: "私は今日は休む方に少し傾いています。その考えも含め、決めつけずに整理してください。",
    },
    school: {
      situation: "架空の授業案への迷いを整理したい",
      firstPrompt: "架空の話です。新しい活動を試したい一方、時間配分が心配です。期待・心配・確認事項に分けてください。",
      followUp: "私は短時間なら試したいです。その条件を入れ、最後の判断は私に残してください。",
    },
    reflectPrompt: "整理された項目を見て、あなた自身が最初に考えたいことは何ですか？",
    related: [9, 23],
  }),
  quest({
    id: 20,
    area: "media",
    title: "AIの案に自分の案を足せ",
    ability: "AI案を完成品にせず自分の考えを加える",
    inputMode: "text",
    daily: {
      situation: "AIの献立案に自分の食べたい物を足したい",
      firstPrompt: "手軽な夕食案を3つ考えてください。これは下書きとして使います。",
      followUp: "私は温かい汁物を一つ足したいです。元の案を完成品にせず、私の案と組み合わせてください。",
    },
    school: {
      situation: "架空の授業案に自分の工夫を加えたい",
      firstPrompt: "架空の授業の終わりにできる振り返り案を3つください。下書きとして考えます。",
      followUp: "私はペアで一言話す時間を加えたいです。その考えとAI案を組み合わせてください。",
    },
    reflectPrompt: "AIの材料にあなた自身の案を加えると、どこが良くなりましたか？",
    related: [7, 24],
  }),
  quest({
    id: 21,
    area: "thinking",
    title: "自分の好みを伝えよ",
    ability: "好みを言葉にする",
    inputMode: "text",
    daily: {
      situation: "自分に合う休み方を探したい",
      firstPrompt: "短い休憩の過ごし方を3つ提案してください。",
      followUp: "私は一人で静かに過ごし、画面を見ない方法が好みです。それに合う案に変えてください。",
    },
    school: {
      situation: "自分らしい公開資料の見せ方を考えたい",
      firstPrompt: "架空の公開資料を見やすくする工夫を3つ挙げてください。",
      followUp: "私は色を増やさず、余白を使う見せ方が好みです。その考えに合わせてください。",
    },
    reflectPrompt: "答えを変えたのは、あなたのどんな好みの言葉でしたか？",
    related: [5, 23],
  }),
  quest({
    id: 22,
    area: "thinking",
    title: "条件を一つずつ足せ",
    ability: "条件を追加する",
    inputMode: "text",
    daily: {
      situation: "外出案を少しずつ自分向けにしたい",
      firstPrompt: "休日の近場での過ごし方を3つ考えてください。",
      followUp: "まず「1時間以内」、次に「雨でもできる」を足します。私は無理なく試せる案を選びたいです。",
    },
    school: {
      situation: "架空の活動案へ条件を順に加えたい",
      firstPrompt: "架空の学級でできる交流活動を3つ考えてください。",
      followUp: "私は「5分以内」、次に「準備物なし」を条件にします。一つずつ反映してください。",
    },
    reflectPrompt: "条件を足した前後で、あなたに合う答えはどう変わりましたか？",
    related: [5, 11],
  }),
  quest({
    id: 23,
    area: "thinking",
    title: "「これは違う」を伝えよ",
    ability: "違和感を言葉にして対話を続ける",
    inputMode: "text",
    daily: {
      situation: "提案は悪くないが何かが合わない",
      firstPrompt: "気分転換のための朝の習慣を3つ考えてください。",
      followUp: "私は早起きを前提にした案には違和感があります。起きる時刻を変えない案にしてください。",
    },
    school: {
      situation: "架空の文案の調子が自分に合わない",
      firstPrompt: "架空の公開お知らせの明るい書き出しを2案ください。",
      followUp: "私は元気すぎる表現が自分の考えと違います。落ち着いた調子に直してください。",
    },
    reflectPrompt: "「これは違う」の理由を、あなたはどんな言葉で伝えられましたか？",
    related: [18, 21],
  }),
  quest({
    id: 24,
    area: "thinking",
    title: "良いところだけ残せ",
    ability: "部分的に採用する",
    inputMode: "paste",
    daily: {
      situation: "提案の一部だけを使いたい",
      firstPrompt: "次の架空の提案文を、使える部分と合わない部分に分けてください。「毎朝30分歩き、記録し、週末に振り返る」",
      followUp: "私は「短く歩く」だけ採用したいです。残りを無理に勧めず、私の案として整えてください。",
    },
    school: {
      situation: "架空の活動案から一部を選びたい",
      firstPrompt: "架空の公開活動案「説明10分、話し合い20分、発表10分」を部分ごとに分けてください。",
      followUp: "私は短い話し合いだけ採用します。その考えを中心に5分の案へ直してください。",
    },
    reflectPrompt: "AI案のどこを採用・修正・不採用にするか、あなたはどう決めましたか？",
    related: [11, 20],
  }),
  quest({
    id: 25,
    area: "thinking",
    title: "「ほかには？」で視野を広げよ",
    ability: "最初の案を唯一とせず別の見方を集める",
    inputMode: "text",
    daily: {
      situation: "最初の解決案以外も見たい",
      firstPrompt: "部屋を片付け始める方法を一つ提案してください。",
      followUp: "私はその方法だけが正解とは思いません。「ほかには？」と別の考え方を3つ出してください。",
    },
    school: {
      situation: "架空の課題への見方を増やしたい",
      firstPrompt: "架空の状況です。話し合いが静かなときの対応を一つ考えてください。",
      followUp: "私は別の理由もありそうだと考えます。個人を決めつけず、ほかの見方を3つください。",
    },
    reflectPrompt: "増えた見方の中で、あなたが確かめたいものと採らないものはどれですか？",
    related: [7, 16],
  }),
  quest({
    id: 26,
    area: "thinking",
    title: "AIに「本当？」と聞け",
    ability: "公開資料を添付し回答を原文と比べる",
    inputMode: "document",
    daily: {
      situation: "AIの説明が公開資料どおりか確かめたい",
      firstPrompt: "個人情報を含まない公的機関の公開資料を添付しました。指定した項目を説明し、根拠の箇所を示してください。",
      followUp: "私はその説明が本当か自分で確かめます。原文の見出しとページを示し、推測は分けてください。",
    },
    school: {
      situation: "公的な教育資料とAI回答を比べたい",
      firstPrompt: "添付した公的教育資料について、指定した項目だけを説明し、該当箇所を示してください。",
      followUp: "私はAIの言葉をそのまま採用しません。原文のページと文脈を示してください。",
    },
    reflectPrompt: "原文へ戻ったとき、AIの答えと違う点をあなたは見つけましたか？",
    factCheck: {
      required: true,
      method: "公的資料の原文・発行元・更新日を確認し、AI回答の各主張を該当ページと照合します。",
    },
    related: [15, 27],
  }),
  quest({
    id: 27,
    area: "thinking",
    title: "確かめ方を教えてもらえ",
    ability: "スクリーンショットや回答から検証方法を尋ねる",
    inputMode: "image",
    daily: {
      situation: "画面に出た情報の確かめ方を知りたい",
      firstPrompt: "個人情報を隠した架空の回答画面です。この内容を自分で確かめる手順と、探す一次情報を教えてください。",
      followUp: "私は検索結果一つだけでは決めたくありません。公的資料と別の情報源を比べる手順にしてください。",
    },
    school: {
      situation: "公開情報のスクリーンショットを検証したい",
      firstPrompt: "情報画面です。学校で使う前に確かめる順番を教えてください。",
      followUp: "私は発行元と更新日も確認したいです。その考えを入れ、原文へたどる方法を示してください。",
    },
    reflectPrompt: "AIが示した確認手順のうち、あなたが実際に行って判断できるものはどれですか？",
    factCheck: {
      required: true,
      method: "スクリーンショットの元ページへ戻り、発行元・更新日・一次資料を確認して複数情報源と比べます。",
    },
    related: [17, 26],
  }),
  quest({
    id: 28,
    area: "thinking",
    title: "AIの言葉を自分に戻せ",
    ability: "自分の言葉に直す",
    inputMode: "document",
    daily: {
      situation: "AIが整えた下書きを自分らしく直したい",
      firstPrompt: "個人情報を含まない架空の下書きを添付しました。かたい表現を3つ挙げて、言い換えの候補を出してください。",
      followUp: "私は普段使わない言葉は残したくありません。候補を材料に、最後は自分で書き直します。",
    },
    school: {
      situation: "架空の公開文書案を自分の文体に戻したい",
      firstPrompt: "添付した文書案から、かたい表現を3つ挙げてください。",
      followUp: "私は簡潔な文体が好みです。候補だけ示し、採用する言葉は私が決めます。",
    },
    reflectPrompt: "AIらしい言葉を外したあと、あなた自身の言葉になったと感じる部分はどこですか？",
    related: [3, 4],
  }),
  quest({
    id: 29,
    area: "thinking",
    title: "自分専用の最初の一言を作れ",
    ability: "よく使う入口を決める",
    inputMode: "document",
    daily: {
      situation: "何を相談するか迷わない入口がほしい",
      firstPrompt: "個人情報を含まない架空のメモを添付しました。日常の困りごとを相談するときの最初の一言を3案ください。",
      followUp: "私は短く、答えを決めつけない言い方が好みです。自分で直せる下書きにしてください。",
    },
    school: {
      situation: "校務相談で使う安全な入口を作りたい",
      firstPrompt: "添付したメモを参考に、校務を整理するときの最初の一言を3案ください。",
      followUp: "私は毎回「個人情報は入れません」と確認したいです。その考えを入れた短い形にしてください。",
    },
    reflectPrompt: "3案から選び直した、あなた専用の最初の一言はどんな形ですか？",
    related: [10, 30],
  }),
  quest({
    id: 30,
    area: "thinking",
    title: "自分の「マイ孫の手」を発見せよ",
    ability: "体験を振り返る",
    inputMode: "text",
    daily: {
      situation: "30回の体験から自分に合う使い道を見つけたい",
      firstPrompt: "これまで試した中で「整理する・言い換える・案を増やす」が役立った場面を、架空例で一つずつ示してください。",
      followUp: "私は自分の体験を思い出して選びます。AIの例を完成品にせず、振り返る質問をしてください。",
    },
    school: {
      situation: "安全に使える自分の校務場面を振り返りたい",
      firstPrompt: "個人情報なしの架空・公開情報だけで試せるAIの使い道を、振り返り用に3分類してください。",
      followUp: "私は安全に続けられる一場面だけ選びます。採用・修正・不採用を自分で決める質問をしてください。",
    },
    reflectPrompt: "AIを使う・直す・使わないをあなた自身で決められる「マイ孫の手」は何ですか？",
    related: [20, 29],
  }),
];
